// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApIGRN1ZCqRMHMtwsgPbDOpaAjXBEje9A',
    appId: '1:987939665701:web:2f7ef0501a57e291108ccc',
    messagingSenderId: '987939665701',
    projectId: 'fir-notification-97cb7',
    authDomain: 'fir-notification-97cb7.firebaseapp.com',
    storageBucket: 'fir-notification-97cb7.appspot.com',
    measurementId: 'G-L06ES3XVEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIEUwZvqAl4hxCGbaXQg1g5Ne9YE7UIfI',
    appId: '1:987939665701:android:fd89788dd4b29b81108ccc',
    messagingSenderId: '987939665701',
    projectId: 'fir-notification-97cb7',
    storageBucket: 'fir-notification-97cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvpYD-R7Q1fRl3l0jiEQ49shk1lKdDuo',
    appId: '1:987939665701:ios:77191cd3b3735569108ccc',
    messagingSenderId: '987939665701',
    projectId: 'fir-notification-97cb7',
    storageBucket: 'fir-notification-97cb7.appspot.com',
    iosBundleId: 'com.example.fakeApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrvpYD-R7Q1fRl3l0jiEQ49shk1lKdDuo',
    appId: '1:987939665701:ios:77191cd3b3735569108ccc',
    messagingSenderId: '987939665701',
    projectId: 'fir-notification-97cb7',
    storageBucket: 'fir-notification-97cb7.appspot.com',
    iosBundleId: 'com.example.fakeApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApIGRN1ZCqRMHMtwsgPbDOpaAjXBEje9A',
    appId: '1:987939665701:web:d661df9422c810cc108ccc',
    messagingSenderId: '987939665701',
    projectId: 'fir-notification-97cb7',
    authDomain: 'fir-notification-97cb7.firebaseapp.com',
    storageBucket: 'fir-notification-97cb7.appspot.com',
    measurementId: 'G-RERVVYX7DR',
  );
}
